//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.SQLCLR.ApiCall.Tests.Unit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.SQLCLR.ApiCall.Tests.Unit.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;country&quot;: [
        ///    {
        ///      &quot;country_id&quot;: &quot;CH&quot;,
        ///      &quot;probability&quot;: 0.068
        ///    },
        ///    {
        ///      &quot;country_id&quot;: &quot;RU&quot;,
        ///      &quot;probability&quot;: 0.054
        ///    },
        ///    {
        ///      &quot;country_id&quot;: &quot;BE&quot;,
        ///      &quot;probability&quot;: 0.052
        ///    },
        ///    {
        ///      &quot;country_id&quot;: &quot;AT&quot;,
        ///      &quot;probability&quot;: 0.045
        ///    },
        ///    {
        ///      &quot;country_id&quot;: &quot;NL&quot;,
        ///      &quot;probability&quot;: 0.044
        ///    }
        ///  ],
        ///  &quot;name&quot;: &quot;test&quot;
        ///}.
        /// </summary>
        internal static string Nationalize_response_name_test {
            get {
                return ResourceManager.GetString("Nationalize_response_name_test", resourceCulture);
            }
        }
    }
}
